In [42]:
# do not touch this cell 
%load_ext jupyter_record


The jupyter_record extension is already loaded. To reload it, use:
  %reload_ext jupyter_record


# Set-up

Make sure that you have completed the set-up instuctions in Assignment 0. 

Every time you create a Jupyter cell in this assignment, it should be annotated with '%%git_commit' at the top. Please do not touch this line of code. If you do not see this line, make sure that you have moved the 'custom.js' file in the right location!


# Data Preprocessing

In this section, you should load your raw training dataset, and create your features for the model. You can find the data here: [shorturl.at/owMPS](https://shorturl.at/owMPS)

**IMPORTANT**: Download your data and place it in the "data" folder. You may run into errors if you place it anywhere else. You can use pandas to import your data from the csv files.

The data files are as following:

- training.csv: Seen/training data. Contains raw features and prediction class ('DepDel15').
- testing_X.csv: Unseen/testing data. Contains only raw features, and no prediction class. 
- readme.html: Information about the features. 



In [2]:
%%git_commit

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('data/training.csv')
print(df.head())

   Unnamed: 0  FlightDate            Airline Origin Dest  Cancelled  Diverted  \
0           0  2018-01-23  Endeavor Air Inc.    ABY  ATL      False     False   
1           1  2018-01-24  Endeavor Air Inc.    ABY  ATL      False     False   
2           2  2018-01-25  Endeavor Air Inc.    ABY  ATL      False     False   
3           3  2018-01-26  Endeavor Air Inc.    ABY  ATL      False     False   
4           4  2018-01-27  Endeavor Air Inc.    ABY  ATL      False     False   

   CRSDepTime  CRSElapsedTime  Distance  ...  DestAirportID  DestAirportSeqID  \
0        1202            62.0     145.0  ...          10397           1039707   
1        1202            62.0     145.0  ...          10397           1039707   
2        1202            62.0     145.0  ...          10397           1039707   
3        1202            62.0     145.0  ...          10397           1039707   
4        1400            60.0     145.0  ...          10397           1039707   

   DestCityMarketID  DestC

In [25]:
%%git_commit
print(df.columns)
filtered = df.select_dtypes(include='number') 
filtered.drop(columns = "Year",inplace = True)
# filtered.columns
filtered['Delay'] = filtered['CRSElapsedTime'] - (filtered['CRSArrTime'] - filtered['CRSArrTime'])
filtered.corr()

Index(['Unnamed: 0', 'FlightDate', 'Airline', 'Origin', 'Dest', 'Cancelled',
       'Diverted', 'CRSDepTime', 'CRSElapsedTime', 'Distance', 'Year',
       'Quarter', 'Month', 'DayofMonth', 'DayOfWeek',
       'Marketing_Airline_Network', 'Operated_or_Branded_Code_Share_Partners',
       'DOT_ID_Marketing_Airline', 'IATA_Code_Marketing_Airline',
       'Operating_Airline', 'DOT_ID_Operating_Airline',
       'IATA_Code_Operating_Airline', 'Tail_Number', 'OriginAirportID',
       'OriginAirportSeqID', 'OriginCityMarketID', 'OriginCityName',
       'OriginState', 'OriginStateFips', 'OriginStateName', 'OriginWac',
       'DestAirportID', 'DestAirportSeqID', 'DestCityMarketID', 'DestCityName',
       'DestState', 'DestStateFips', 'DestStateName', 'DestWac', 'DepDel15',
       'CRSArrTime'],
      dtype='object')


Unnamed: 0  CRSDepTime  CRSElapsedTime  Distance  \
Unnamed: 0                  1.000000    0.002603       -0.000369  0.015777   
CRSDepTime                  0.002603    1.000000       -0.018113 -0.010256   
CRSElapsedTime             -0.000369   -0.018113        1.000000  0.981010   
Distance                    0.015777   -0.010256        0.981010  1.000000   
Quarter                    -0.109568   -0.004631       -0.029311 -0.031697   
Month                      -0.003606   -0.004569       -0.027327 -0.030066   
DayofMonth                 -0.001773   -0.000125        0.002841  0.002222   
DayOfWeek                   0.035479    0.007462        0.011835  0.013605   
DOT_ID_Marketing_Airline    0.002479    0.001825        0.169590  0.140350   
DOT_ID_Operating_Airline   -0.021963   -0.004170       -0.021095 -0.071350   
OriginAirportID             0.005287   -0.022770        0.030918  0.056243   
OriginAirportSeqID          0.005287   -0.022770        0.030918  0.056243   
OriginCityMarketID         -0.004169   -0.047597       -0.013791 -0.004433   
OriginStateFips             0.001619   -0.024678       -0.035782 -0.071713   
OriginWac                   0.009182   -0.007698       -0.029188  0.035640   
DestAirportID               0.005452    0.021534        0.069284  0.056783   
DestAirportSeqID            0.005452    0.021533        0.069285  0.056784   
DestCityMarketID           -0.004222    0.056129       -0.009709 -0.004146   
DestStateFips               0.001601    0.019163       -0.079745 -0.072076   
DestWac                     0.009093    0.022089        0.062229  0.035608   
DepDel15                    0.025902    0.172097        0.013892  0.012557   
CRSArrTime                 -0.010884    0.684092        0.023671  0.018664   
Delay                      -0.000369   -0.018113        1.000000  0.981010   

                           Quarter     Month  DayofMonth  DayOfWeek  \
Unnamed: 0               -0.109568 -0.003606   -0.001773   0.035479   
CRSDepTime               -0.004631 -0.004569   -0.000125   0.007462   
CRSElapsedTime           -0.029311 -0.027327    0.002841   0.011835   
Distance                 -0.031697 -0.030066    0.002222   0.013605   
Quarter                   1.000000  0.971519    0.003414   0.005970   
Month                     0.971519  1.000000    0.003857   0.017872   
DayofMonth                0.003414  0.003857    1.000000   0.009201   
DayOfWeek                 0.005970  0.017872    0.009201   1.000000   
DOT_ID_Marketing_Airline -0.035256 -0.033496    0.000578   0.011740   
DOT_ID_Operating_Airline  0.056531  0.056361    0.001053   0.005979   
OriginAirportID          -0.020354 -0.019373   -0.000264   0.002053   
OriginAirportSeqID       -0.020354 -0.019372   -0.000264   0.002053   
OriginCityMarketID       -0.009130 -0.009298    0.000258   0.002612   
OriginStateFips           0.045035  0.044553    0.000423  -0.002444   
OriginWac                -0.036180 -0.035855   -0.001086  -0.002658   
DestAirportID            -0.020329 -0.019344   -0.000290   0.001691   
DestAirportSeqID         -0.020329 -0.019344   -0.000290   0.001691   
DestCityMarketID         -0.009187 -0.009359    0.000157   0.002557   
DestStateFips             0.044943  0.044459    0.000397  -0.002260   
DestWac                  -0.036138 -0.035806   -0.001060  -0.002897   
DepDel15                 -0.019862 -0.018527   -0.004709  -0.004930   
CRSArrTime                0.005901  0.005352   -0.001685   0.007849   
Delay                    -0.029311 -0.027327    0.002841   0.011835   

                          DOT_ID_Marketing_Airline  DOT_ID_Operating_Airline  \
Unnamed: 0                                0.002479                 -0.021963   
CRSDepTime                                0.001825                 -0.004170   
CRSElapsedTime                            0.169590                 -0.021095   
Distance                                  0.140350                 -0.071350   
Quarter                                  -0.0352

In [34]:
%%git_commit
from sklearn.preprocessing import OneHotEncoder

ohe_airports = df['OriginAirportID'].to_numpy()
ohe = OneHotEncoder(sparse=False)

ohe_airports = ohe.fit_transform(ohe_airports.reshape(-1,1))
print(ohe_airports)
print(ohe_airports[0])

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0

# Model Prediction

In this section, you should import relevant modeling/scikit-learn libraries and create a prediction model from your features. You should carefuly evaluate how your model performs based on the data you already have.

**Hint**: We are using a real world dataset with low correlation between the raw features and prediction class. You may have to carefully think about how to hand-engineer features from the raw features to capture correlation using a machine learning model.


**Hint 2**: When the instructors ran this assignment, we achieved an accuracy of 0.74 and AUC score of 0.54 on held out data. We do not expect high accuracy for this task, but your goal is to create a prediction model that is better than the simplest baseline - i.e. a model that predictions the majority class for all samples.


In [44]:
%%git_commit
df.dropna(inplace = True)
result = df.select_dtypes(include='number')

print(result.head())
cr = result.corr()
cr = cr[abs(cr["DepDel15"]) > .02]
print(cr)

X = result[['CRSDepTime','CRSArrTime','OriginAirportID']].to_numpy()
Y = result['DepDel15'].to_numpy()

from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


   Unnamed: 0  CRSDepTime  CRSElapsedTime  Distance  Year  Quarter  Month  \
0           0        1202            62.0     145.0  2018        1      1   
1           1        1202            62.0     145.0  2018        1      1   
2           2        1202            62.0     145.0  2018        1      1   
3           3        1202            62.0     145.0  2018        1      1   
4           4        1400            60.0     145.0  2018        1      1   

   DayofMonth  DayOfWeek  DOT_ID_Marketing_Airline  ...  OriginCityMarketID  \
0          23          2                     19790  ...               30146   
1          24          3                     19790  ...               30146   
2          25          4                     19790  ...               30146   
3          26          5                     19790  ...               30146   
4          27          6                     19790  ...               30146   

   OriginStateFips  OriginWac  DestAirportID  DestAirportSeqID

In [ ]:
%%git_commit
print(X)

In [45]:
%%git_commit
from sklearn.linear_model import LogisticRegression

X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.33)

print(len(X_train))
model = LogisticRegression()
model.fit(X_train,Y_train)

Y_hat = model.predict(X_train)


3753951


In [6]:
%%git_commit
# (sum(Y_test) - sum(Y_hat))/len(Y_test[Y_test == 1])

Y_hat


array([0., 0., 0., ..., 0., 0., 0.])

# Final Evaluation

In this section, you should use your prediction model on held out data. For each sample in 'testing_X.csv', generate a binary prediction on whether the flight will be delayed by 15min or more.

**Important**: Create a csv file named that is a list of your predictions. It should be named './data/[CNET_ID]_final_assignment.csv' file, and contain only one row and columns equal to the sample size. 

**IMPORTANT**: Make sure that you create the new file in the "data" folder. You may run into errors if you place it anywhere else. 

Upload the '.csv' file here: [shorturl.at/aox05](https://shorturl.at/aox05)

This is your submission for the project! A part of your assessment will be on performance on this unseen dataset, and whether you can do better than majority class prediction. 

Note that you do not have true classification labels on this dataset.


In [ ]:
%%git_commit
df2 = pd.read_csv('data/testing_X.csv')
df2.head()


In [ ]:
%%git_commit
